/*
 * file : Avanzate.java
 */
package progettopastoreluca;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * Finestra di dialogo per il settaggio dei parametri per connessione al database da remoto,
 * richiamata dalla classe Login
 * 
 * @author Luca Pastore N86002599
 * @version 2019
 */
public class AvanzateLogin extends javax.swing.JDialog {
    /**
     * Creates new form avanzateLogin
     * @param parent classe chiamante
     * @param title titolo della JDialog
     */
    public AvanzateLogin(java.awt.Dialog parent, String title) {
        super(parent, title);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setButton = new javax.swing.JButton();
        annullaButton = new javax.swing.JButton();
        portaLabel = new javax.swing.JLabel();
        servizioLabel = new javax.swing.JLabel();
        servizioTextField = new javax.swing.JTextField();
        hostTextField = new javax.swing.JTextField();
        hostLabel = new javax.swing.JLabel();
        istrLabel3 = new javax.swing.JLabel();
        portaSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        setButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setButton.setText("IMPOSTA");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        annullaButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        annullaButton.setText("ANNULLA");
        annullaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaButtonActionPerformed(evt);
            }
        });

        portaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        portaLabel.setText("PORTA");

        servizioLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        servizioLabel.setText("SERVIZIO");

        servizioTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        servizioTextField.setText("xe");

        hostTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hostTextField.setText("localhost");

        hostLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hostLabel.setText("HOST");

        istrLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        istrLabel3.setText("Ulteriori settaggi per la connessione al Database");

        portaSpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        portaSpinner.setModel(new javax.swing.SpinnerNumberModel(1521, 1, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(istrLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(servizioLabel)
                            .addComponent(hostLabel)
                            .addComponent(portaLabel))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(servizioTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hostTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(portaSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(setButton)
                            .addComponent(annullaButton))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(istrLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hostLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(servizioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(servizioLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(portaLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(portaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(annullaButton)
                        .addGap(21, 21, 21))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
        Database.host = hostTextField.getText();
        Database.porta = (int)portaSpinner.getValue();
        Database.servizio = servizioTextField.getText();
        this.setVisible(false);
    }//GEN-LAST:event_setButtonActionPerformed

    private void annullaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annullaButtonActionPerformed
        dispose();
    }//GEN-LAST:event_annullaButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annullaButton;
    private javax.swing.JLabel hostLabel;
    private javax.swing.JTextField hostTextField;
    private javax.swing.JLabel istrLabel3;
    private javax.swing.JLabel portaLabel;
    private javax.swing.JSpinner portaSpinner;
    private javax.swing.JLabel servizioLabel;
    private javax.swing.JTextField servizioTextField;
    private javax.swing.JButton setButton;
    // End of variables declaration//GEN-END:variables
}
