/*
 * file : SearchSchema.java
 */
package progettopastoreluca;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Pannello che permette di effettuare la ricerca di un elemento Schema all'interno del database
 * più tutti gli oggetto che gli appartengono
 * 
 * @author Luca Pastore N86002599
 * @version 2019
 */
public class SearchSchema extends javax.swing.JPanel {

    private TableModel schemaTableModel; //modello tabella visualizzazione Schema cercato
    private TableModel objectTableModel; //modello tabella visualizzazione oggetti appartenenti a Schema cercato
    
    private int schemaTrovato; //indicherà se la ricrca dello Schema ha prodotto risultati o meno
    private final int NO = 0;
    private final int SI = 1;
    
    /**
     * Creates new form SearchSchema
     */
    public SearchSchema() {
        this.setSize(770,418);
        initComponents();
        
        schemaTrovato = NO;
        schemaTable.setModel(new DefaultTableModel());
        objectTable.setModel(new DefaultTableModel());
    }

    //Metodo che mostra a video l'errore generatosi durante l'operazione SQL
    public void mostraErrore(SQLException e) {
        String msg;
        
        msg = "Codice Errore: " + e.getErrorCode() + "\n";
        msg += "Messaggio: " + e.getMessage() + "\n";
        msg += "SQLState: " + e.getSQLState() + "\n";

        JOptionPane.showMessageDialog(this, msg, "Errore", JOptionPane.ERROR_MESSAGE);
    }
    
    //riempe la tabella objectTble con gli oggetti selezionati
    private void creaObjectTable(ResultSet rs){
        try{
            objectTableModel = new TableModel(rs);
            objectTableModel.setEditable(false);
            objectTableModel.setNumColumn();
                
            while(rs.next()) {
                int riga = objectTableModel.getRowCount(); 
                objectTableModel.setRowCount(objectTableModel.getRowCount() + 1); //nuova riga
                for(int c = 0; c < objectTableModel.getColumnCount(); c++) {
                    Object valore = rs.getObject(c+1);
                    objectTableModel.setValueAt(valore, riga, c);
                }
            }
                
            objectTable.setModel(objectTableModel);
        }catch(SQLException e){
            mostraErrore(e);
        }
    }
    
    //in base al RadioButton selezionato, recupera le righe dalla tabella corrispondente e le mostra nell'objectTable
    private void mostraOggetti(String query){
        PreparedStatement pstmt = null;
        ResultSet rs;
        boolean continua = false;
        
        if(schemaTrovato == SI){ 
            try{
                pstmt = Database.getDefaultConnection().prepareStatement(query + " WHERE schema = ?");                
                
                if(schemaTable.getRowCount() == 1){
                    pstmt.setString(1, schemaTable.getValueAt(0, 0).toString());
                    continua = true;
                    
                }else if(schemaTable.getSelectedRow() != -1){
                    pstmt.setString(1, schemaTable.getValueAt(schemaTable.getSelectedRow(), 0).toString());
                    continua = true;
                }else{
                    JOptionPane.showMessageDialog(this, "ERRORE: Selezionare prima una riga !", "Errore", JOptionPane.ERROR_MESSAGE);
                } 
                
                if(continua){
                    rs = pstmt.executeQuery();
                    creaObjectTable(rs);
                }
                
                if(pstmt != null) pstmt.close();
            }catch(SQLException e){
                mostraErrore(e);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        objectButtonGroup = new javax.swing.ButtonGroup();
        searchLabel = new javax.swing.JLabel();
        schemaTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        schemaTable = new javax.swing.JTable();
        selectLabel = new javax.swing.JLabel();
        oggLabel = new javax.swing.JLabel();
        assertRadioButton = new javax.swing.JRadioButton();
        domRadioButton = new javax.swing.JRadioButton();
        procRadioButton = new javax.swing.JRadioButton();
        seqRadioButton = new javax.swing.JRadioButton();
        tabRadioButton = new javax.swing.JRadioButton();
        trigRadioButton = new javax.swing.JRadioButton();
        vincoloRadioButton = new javax.swing.JRadioButton();
        vistaRadioButton = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        objectTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        searchLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        searchLabel.setText("Inserire il nome dello Schema da cercare : ");

        schemaTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        searchButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        searchButton.setText("Cerca");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        schemaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(schemaTable);

        selectLabel.setText("Di seguito verranno mostrati tutti gli oggetti appartenenti allo Schema cercato; ");

        oggLabel.setText("Selezionare un bottone per visualizzare gli oggetti corrispondenti:");

        objectButtonGroup.add(assertRadioButton);
        assertRadioButton.setText("Asserzioni");
        assertRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assertRadioButtonActionPerformed(evt);
            }
        });

        objectButtonGroup.add(domRadioButton);
        domRadioButton.setText("Domini");
        domRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domRadioButtonActionPerformed(evt);
            }
        });

        objectButtonGroup.add(procRadioButton);
        procRadioButton.setText("Procedure");
        procRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procRadioButtonActionPerformed(evt);
            }
        });

        objectButtonGroup.add(seqRadioButton);
        seqRadioButton.setText("Sequenze");
        seqRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seqRadioButtonActionPerformed(evt);
            }
        });

        objectButtonGroup.add(tabRadioButton);
        tabRadioButton.setText("Tabelle");
        tabRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabRadioButtonActionPerformed(evt);
            }
        });

        objectButtonGroup.add(trigRadioButton);
        trigRadioButton.setText("Trigger");
        trigRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trigRadioButtonActionPerformed(evt);
            }
        });

        objectButtonGroup.add(vincoloRadioButton);
        vincoloRadioButton.setText("Vincoli");
        vincoloRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vincoloRadioButtonActionPerformed(evt);
            }
        });

        objectButtonGroup.add(vistaRadioButton);
        vistaRadioButton.setText("Viste");
        vistaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vistaRadioButtonActionPerformed(evt);
            }
        });

        objectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(objectTable);

        jLabel2.setText("Se la ricerca ha prodotto più risultati, selezionare la riga a cui si è interessati, per un solo risultato non è necessario selezionare una riga");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 31, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(schemaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assertRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(domRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(procRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(seqRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(tabRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(trigRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(vincoloRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(vistaRadioButton))
                            .addComponent(oggLabel)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(schemaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectLabel)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(oggLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assertRadioButton)
                    .addComponent(domRadioButton)
                    .addComponent(procRadioButton)
                    .addComponent(seqRadioButton)
                    .addComponent(tabRadioButton)
                    .addComponent(trigRadioButton)
                    .addComponent(vincoloRadioButton)
                    .addComponent(vistaRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //se il tatsto Cerca viene premuto e lo schemaTextField non è vuota, allora
    //viene eseguita l'istruzione SELECT che recuoera la riga dello Schema cercato e 
    //la posiziona nella schemaTable
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        PreparedStatement pstmt;
        ResultSet rs;
        String query = "SELECT * FROM schema1 ";

        if(!schemaTextField.getText().equals("")){
            query += " WHERE nomeSchema = ?";
        }
        
        try{
            pstmt = Database.getDefaultConnection().prepareStatement(query,  ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            if(!schemaTextField.getText().equals("")){
                pstmt.setString(1, schemaTextField.getText());
            }
            rs = pstmt.executeQuery();

            if(rs.last()){
                rs.beforeFirst();

                schemaTableModel = new TableModel(rs);
                schemaTableModel.setEditable(false);
                schemaTableModel.setNumColumn();

                while(rs.next()) {
                    int riga = schemaTableModel.getRowCount();
                    schemaTableModel.setRowCount(schemaTableModel.getRowCount() + 1); //nuova riga
                    for(int c = 0; c < schemaTableModel.getColumnCount(); c++) {
                        Object valore = rs.getObject(c+1);
                        schemaTableModel.setValueAt(valore, riga, c);
                    }
                }

                schemaTrovato = SI;
                schemaTable.setModel(schemaTableModel);
            }else{
                JOptionPane.showMessageDialog(this, "Nessuno Schema trovato !", "Ricerca vuota", JOptionPane.WARNING_MESSAGE);
                schemaTable.setModel(new DefaultTableModel());
                objectTable.setModel(new DefaultTableModel());
                schemaTrovato = NO;
            }

            pstmt.close();
        }catch(SQLException e){
            mostraErrore(e);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    //recupera e mostra nella objectTable le Asserzioni appartenenti allo Schema cercato
    private void assertRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assertRadioButtonActionPerformed
        mostraOggetti("SELECT nomeAsserzione, ClausolaNotExists, Schema FROM asserzione");
    }//GEN-LAST:event_assertRadioButtonActionPerformed

    //recupera e mostra nella objectTable i Domini appartenenti allo Schema cercato
    private void domRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domRadioButtonActionPerformed
        mostraOggetti("SELECT nomeDominio, Tipo, Schema FROM dominio");
    }//GEN-LAST:event_domRadioButtonActionPerformed

    //recupera e mostra nella objectTable le Procedure appartenenti allo Schema cercato
    private void procRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procRadioButtonActionPerformed
        mostraOggetti("SELECT nomeProcedura, bloccoCodice, tipo, tipoRitorno, proprietario FROM procedura");
    }//GEN-LAST:event_procRadioButtonActionPerformed

    //recupera e mostra nella objectTable le Sequenze appartenenti allo Schema cercato
    private void seqRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seqRadioButtonActionPerformed
        mostraOggetti("SELECT nomeSeq, incremento, valIniziale, valMax, cycle, proprietario FROM sequenza");
    }//GEN-LAST:event_seqRadioButtonActionPerformed

    //recupera e mostra nella objectTable le Tabelle appartenenti allo Schema cercato
    private void tabRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabRadioButtonActionPerformed
        mostraOggetti("SELECT nomeTabella, dataCreazione, ultimaModifica, proprietario FROM tabella");
    }//GEN-LAST:event_tabRadioButtonActionPerformed

    //recupera e mostra nella objectTable i Trigger appartenenti allo Schema cercato
    private void trigRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trigRadioButtonActionPerformed
        mostraOggetti("SELECT nomeTrigger, tempo, forEachRow, CondizioneWhen, causa, bloccoCodice, oggetto,proprietario FROM infoTrigger");
    }//GEN-LAST:event_trigRadioButtonActionPerformed

    //recupera e mostra nella objectTable i Vincoli appartenenti allo Schema cercato
    private void vincoloRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vincoloRadioButtonActionPerformed
        mostraOggetti("SELECT nomeVincolo, tipoVincolo, condizioneCheck, stato, tabella, proprietario FROM infoVincolo");
    }//GEN-LAST:event_vincoloRadioButtonActionPerformed

    //recupera e mostra nella objectTable le Viste appartenenti allo Schema cercato
    private void vistaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vistaRadioButtonActionPerformed
        mostraOggetti("SELECT nomeVista, query, proprietario FROM vista");
    }//GEN-LAST:event_vistaRadioButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton assertRadioButton;
    private javax.swing.JRadioButton domRadioButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup objectButtonGroup;
    private javax.swing.JTable objectTable;
    private javax.swing.JLabel oggLabel;
    private javax.swing.JRadioButton procRadioButton;
    private javax.swing.JTable schemaTable;
    private javax.swing.JTextField schemaTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel selectLabel;
    private javax.swing.JRadioButton seqRadioButton;
    private javax.swing.JRadioButton tabRadioButton;
    private javax.swing.JRadioButton trigRadioButton;
    private javax.swing.JRadioButton vincoloRadioButton;
    private javax.swing.JRadioButton vistaRadioButton;
    // End of variables declaration//GEN-END:variables
}
