/*
 * file : Search.java
 */
package progettopastoreluca;

/**
 * Pannello che permette di accedere alle funzionalità di ricerca
 * 
 * @author Luca Pastore N86002599
 * @version 2019
 */
public class Search extends javax.swing.JPanel {
    private SearchSchema sS; //pannello per effettuare la ricerca di un elemento Schema
    private SearchUser sU; //pannello per effettuare la ricerca di un elemento Utente
    private SearchRuolo sR; //pannello per effettuare la ricerca di un elemento Ruolo
    private SearchTabella sT; //pannello per effettuare la ricerca di un elemento Tabella
    private SearchDominio sD; //pannello per effettuare la ricerca di un elemento Dominio
    private SearchTrigger sTr; //pannello per effettuare la ricerca di un elemento Trigger
    private SearchProcedura sP; //pannello per effettuare la ricerca di un elemento Procedura
    private SearchViewSeqAssert sVSA; //pannello per effettuare la ricerca di un elemento Vista o Sequenza o Asserzione
    private SearchVincolo sV; //pannello per effettuare la ricerca di un elemento Vincolo
    
    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
        oggComboBox.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchOptionPanel = new javax.swing.JPanel();
        userRadioButton = new javax.swing.JRadioButton();
        ruoloRadioButton = new javax.swing.JRadioButton();
        schemaRadioButton = new javax.swing.JRadioButton();
        oggRadioButton = new javax.swing.JRadioButton();
        oggComboBox = new javax.swing.JComboBox<>();
        searchPanel = new javax.swing.JPanel();

        searchLabel.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(0, 51, 255));
        searchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchLabel.setText("SELEZIONARE L' ELEMENTO CHE SI DESIDERA CERCARE");
        searchLabel.setToolTipText("");

        searchButtonGroup.add(userRadioButton);
        userRadioButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        userRadioButton.setText("Utente");
        userRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRadioButtonActionPerformed(evt);
            }
        });

        searchButtonGroup.add(ruoloRadioButton);
        ruoloRadioButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ruoloRadioButton.setText("Ruolo");
        ruoloRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruoloRadioButtonActionPerformed(evt);
            }
        });

        searchButtonGroup.add(schemaRadioButton);
        schemaRadioButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        schemaRadioButton.setText("Schema");
        schemaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemaRadioButtonActionPerformed(evt);
            }
        });

        searchButtonGroup.add(oggRadioButton);
        oggRadioButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        oggRadioButton.setText("Oggetto DB");
        oggRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oggRadioButtonActionPerformed(evt);
            }
        });

        oggComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oggComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tabella", "Dominio", "Vincolo", "Asserzione", "Sequenza", "Trigger", "Procedura/Funzione", "Vista" }));
        oggComboBox.setSelectedIndex(-1);
        oggComboBox.setEnabled(false);
        oggComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oggComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchOptionPanelLayout = new javax.swing.GroupLayout(searchOptionPanel);
        searchOptionPanel.setLayout(searchOptionPanelLayout);
        searchOptionPanelLayout.setHorizontalGroup(
            searchOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchOptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userRadioButton)
                .addGap(18, 18, 18)
                .addComponent(ruoloRadioButton)
                .addGap(18, 18, 18)
                .addComponent(schemaRadioButton)
                .addGap(18, 18, 18)
                .addComponent(oggRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oggComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchOptionPanelLayout.setVerticalGroup(
            searchOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchOptionPanelLayout.createSequentialGroup()
                .addGroup(searchOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userRadioButton)
                    .addComponent(ruoloRadioButton)
                    .addComponent(schemaRadioButton)
                    .addComponent(oggRadioButton)
                    .addComponent(oggComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchOptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchOptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void oggRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oggRadioButtonActionPerformed
        oggComboBox.setEnabled(true);
        searchPanel.removeAll();
        searchPanel.revalidate();
        searchPanel.repaint();
    }//GEN-LAST:event_oggRadioButtonActionPerformed

    //crea un oggetto SearchSchema per la ricerca di Schemi e lo aggiunge al SearchPanel
    private void schemaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemaRadioButtonActionPerformed
        searchPanel.removeAll();
        sS = new SearchSchema();
        searchPanel.add(sS);
        searchPanel.revalidate();
        searchPanel.repaint();
        oggComboBox.setSelectedIndex(-1);
        oggComboBox.setEnabled(false);
    }//GEN-LAST:event_schemaRadioButtonActionPerformed

    //crea un oggetto SearchRuolo per la ricerca del ruolo e lo aggiunge al SearchPanel
    private void ruoloRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruoloRadioButtonActionPerformed
        searchPanel.removeAll();
        sR = new SearchRuolo();
        searchPanel.add(sR);
        searchPanel.revalidate();
        searchPanel.repaint();
        oggComboBox.setSelectedIndex(-1);
        oggComboBox.setEnabled(false);
    }//GEN-LAST:event_ruoloRadioButtonActionPerformed

    //crea un oggetto SearchUser per la ricerca di utenti e lo aggiunge al SearchPanel
    private void userRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRadioButtonActionPerformed
        searchPanel.removeAll();
        sU = new SearchUser();
        searchPanel.add(sU);
        searchPanel.revalidate();
        searchPanel.repaint();
        oggComboBox.setSelectedIndex(-1);
        oggComboBox.setEnabled(false);
    }//GEN-LAST:event_userRadioButtonActionPerformed

    private void oggComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oggComboBoxActionPerformed
        if(oggComboBox.getSelectedIndex() != -1){
            switch(oggComboBox.getSelectedItem().toString()){
                //crea un oggetto SearchTabella che permette la ricerca di una Tabella e lo aggiunge al searchPanel
                case "Tabella":
                    searchPanel.removeAll();
                    sT = new SearchTabella();
                    searchPanel.add(sT);
                    searchPanel.revalidate();
                    searchPanel.repaint();
                break;
                
                //crea un oggetto SearchDominio che permette la ricerca di un Dominio e lo aggiunge al searchPanel
                case "Dominio":
                    searchPanel.removeAll();
                    sD = new SearchDominio();
                    searchPanel.add(sD);
                    searchPanel.revalidate();
                    searchPanel.repaint();
                break;
                
                //crea un oggetto SearchTrigger che permette la ricerca di un Trigger e lo aggiunge al searchPanel
                case "Trigger":
                    searchPanel.removeAll();
                    sTr = new SearchTrigger();
                    searchPanel.add(sTr);
                    searchPanel.revalidate();
                    searchPanel.repaint();
                break;
                
                //crea un oggetto SearchProcedura che permette la ricerca di una Procedura / Funzione e lo aggiunge al searchPanel
                case "Procedura/Funzione":
                    searchPanel.removeAll();
                    sP = new SearchProcedura();
                    searchPanel.add(sP);
                    searchPanel.revalidate();
                    searchPanel.repaint();
                break;
                
                //crea un oggetto SearchViewSeqAssert che permette la ricerca di un' Asserzione e lo aggiunge al searchPanel
                case "Asserzione":
                    searchPanel.removeAll();
                    sVSA = new SearchViewSeqAssert(SearchViewSeqAssert.ASSERT);
                    searchPanel.add(sVSA);
                    searchPanel.revalidate();
                    searchPanel.repaint();
                break;
                
                //crea un oggetto SearchViewSeqAssert che permette la ricerca di una Vista e lo aggiunge al searchPanel
                case "Vista":
                    searchPanel.removeAll();
                    sVSA = new SearchViewSeqAssert(SearchViewSeqAssert.VISTA);
                    searchPanel.add(sVSA);
                    searchPanel.revalidate();
                    searchPanel.repaint();
                break;
                
                //crea un oggetto SearchViewSeqAssert che permette la ricerca di una Sequenza e lo aggiunge al searchPanel
                case "Sequenza":
                    searchPanel.removeAll();
                    sVSA = new SearchViewSeqAssert(SearchViewSeqAssert.SEQ);
                    searchPanel.add(sVSA);
                    searchPanel.revalidate();
                    searchPanel.repaint();
                break;
                
                //crea un oggetto SearchVincolo che permette la ricerca di un Vincolo e lo aggiunge al searchPanel
                case "Vincolo":
                    searchPanel.removeAll();
                    sV = new SearchVincolo();
                    searchPanel.add(sV);
                    searchPanel.revalidate();
                    searchPanel.repaint();
                break;
            } 
        }
    }//GEN-LAST:event_oggComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> oggComboBox;
    private javax.swing.JRadioButton oggRadioButton;
    private javax.swing.JRadioButton ruoloRadioButton;
    private javax.swing.JRadioButton schemaRadioButton;
    private javax.swing.ButtonGroup searchButtonGroup;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchOptionPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JRadioButton userRadioButton;
    // End of variables declaration//GEN-END:variables
}
