/**
 * file : InsertVista.java
 */
package progettopastoreluca;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 * Pannello che permette l'aggiunta dell'elemento vista nel database;
 * 
 * @author Luca Pastore N86002599
 * @version 2019
 */
public class InsertVista extends javax.swing.JPanel {

    private PreparedStatement pstmt = null;
    private final String queryIns = "INSERT INTO vista(NomeVista, Query, Proprietario, Schema) VALUES(?, ?, ?, ?)";
    private int righeInserite = 0;
    
    /**
     * Creates new form InsertVista
     */
    public InsertVista() {
       this.setSize(770,423);
        initComponents();
    }
    
    //azzera i campi input del pannello
    public void pulisciInput(){
        nomeVistaTextField.setText("");
        proprVistaComboBox.setSelectedIndex(-1);
        schemaVistaComboBox.setSelectedIndex(-1);
        queryVistaTextArea.setText("");
    }
    
    
    //metodo che controlla se i campi di input sono stati riempiti o ne rimane almeno uno vuoto
    private boolean campiVuoti(){
        boolean tmp;
        
        tmp = nomeVistaTextField.getText().equals("") || proprVistaComboBox.getSelectedIndex() == -1 || schemaVistaComboBox.getSelectedIndex() == -1 || queryVistaTextArea.getText().equals("");
        
        return tmp;
    }
    
    //metodo utilizzato per riempire la proprVistaComboBox con gli username degli utenti che posseggono i permessi necessari alla creazione di una vista
    private void riempiProprVistaComboBox(){
        Statement stmt;
        ResultSet rst;
        String query = "SELECT U.username FROM utente U JOIN compRuoloSistema C ON U.ruolo = C.ID_ruolo WHERE C.ID_privSis = 'ALL PRIVILEGIES' OR C.ID_privSis = 'CREATE VIEW'";
        
        try{
            stmt = Database.getDefaultConnection().createStatement();
            rst = stmt.executeQuery(query);
            
            while(rst.next()){
                proprVistaComboBox.addItem(rst.getString(1));
            }
            
            proprVistaComboBox.setSelectedIndex(-1);
            
            stmt.close();
        }catch(SQLException e){
            mostraErrore(e);
        }
    }
    
    //metodo utilizzato per riempire la schemaVistaComboBox con gli schemi presenti nel database
    private void riempiSchemaVistaComboBox(){
        Statement stmt;
        ResultSet rst;
        String query = "SELECT nomeSchema FROM schema1";
        
        try{
            stmt = Database.getDefaultConnection().createStatement();
            rst = stmt.executeQuery(query);
            
            while(rst.next()){
                schemaVistaComboBox.addItem(rst.getString(1));
            }
            
            schemaVistaComboBox.setSelectedIndex(-1);
            
            stmt.close();
        }catch(SQLException e){
            mostraErrore(e);
        }
    }
    
    //metodo richiamato nella JPanel Insert utilizzato per riempire le JComboBox presenti in questo JPanel
    //in modo che contengano sempre dati aggiurnati  ai cambiamenti che avvengono nel DB
    public void riempiComboBox(){
        proprVistaComboBox.removeAllItems();
        schemaVistaComboBox.removeAllItems();
        this.riempiProprVistaComboBox();
        this.riempiSchemaVistaComboBox();
    }
    
    //Metodo che mostra a video l'errore generatosi durante l'inserimento di un elemento schema nel database
    private void mostraErrore(SQLException e) {
        String msg;
        
        msg = "Codice Errore: " + e.getErrorCode() + "\n";
        msg += "Messaggio: " + e.getMessage() + "\n";
        msg += "SQLState: " + e.getSQLState() + "\n";

        JOptionPane.showMessageDialog(this, msg, "Errore", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        istruzioni1 = new javax.swing.JLabel();
        istruzioni2 = new javax.swing.JLabel();
        istruzioni3 = new javax.swing.JLabel();
        nomeVistaLabel = new javax.swing.JLabel();
        nomeVistaTextField = new javax.swing.JTextField();
        queryVistaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryVistaTextArea = new javax.swing.JTextArea();
        schemaVistaLabel = new javax.swing.JLabel();
        schemaVistaComboBox = new javax.swing.JComboBox<>();
        proprVistaLabel = new javax.swing.JLabel();
        proprVistaComboBox = new javax.swing.JComboBox<>();
        insertVistaButton1 = new javax.swing.JButton();
        annullaButton = new javax.swing.JButton();
        campoObbLabel = new javax.swing.JLabel();

        istruzioni1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        istruzioni1.setText("Inserire di seguito i dati relativi alla vista che si vuole inserire. ");

        istruzioni2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        istruzioni2.setText("Nel campo Query va inserito il contenuto della vista. Nel campo Proprietario verranno visualizzati solo  ");

        istruzioni3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        istruzioni3.setText("gli utenti che hanno i permessi necessari alla creazione di una Vista");

        nomeVistaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomeVistaLabel.setText("Nome Vista  *");

        nomeVistaTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        queryVistaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        queryVistaLabel.setText("Query  *");

        queryVistaTextArea.setColumns(20);
        queryVistaTextArea.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        queryVistaTextArea.setRows(5);
        jScrollPane1.setViewportView(queryVistaTextArea);

        schemaVistaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        schemaVistaLabel.setText("Schema  *");

        schemaVistaComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        proprVistaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        proprVistaLabel.setText("Proprietario  *");

        proprVistaComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        insertVistaButton1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        insertVistaButton1.setText("Inserisci Vista");
        insertVistaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertVistaButton1ActionPerformed(evt);
            }
        });

        annullaButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        annullaButton.setText("Annulla");
        annullaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaButtonActionPerformed(evt);
            }
        });

        campoObbLabel.setText("*  Campo obbligatorio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(istruzioni1)
                    .addComponent(istruzioni2)
                    .addComponent(istruzioni3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(schemaVistaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(queryVistaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nomeVistaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(proprVistaLabel)))
                            .addComponent(campoObbLabel))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(insertVistaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(annullaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(proprVistaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeVistaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(schemaVistaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(istruzioni1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(istruzioni2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(istruzioni3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeVistaLabel)
                    .addComponent(nomeVistaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(queryVistaLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schemaVistaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schemaVistaLabel))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proprVistaLabel)
                    .addComponent(proprVistaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertVistaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annullaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoObbLabel))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //annulla inserimento di un elemento vista
    private void annullaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annullaButtonActionPerformed
        pulisciInput();
    }//GEN-LAST:event_annullaButtonActionPerformed

    //inserisce un elemento vista all'interno del database
    private void insertVistaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertVistaButton1ActionPerformed
        try{ 
            if(campiVuoti()){
                JOptionPane.showMessageDialog(this, "Prima di effettuare l'inserimento della vista\nriempire tutti i campi obbligatori !", "Attenzione", JOptionPane.WARNING_MESSAGE);
            }else{
                pstmt = Database.getDefaultConnection().prepareStatement(queryIns);            
            
                pstmt.setString(1, nomeVistaTextField.getText());
                pstmt.setString(2, queryVistaTextArea.getText());
                pstmt.setString(3, (String)proprVistaComboBox.getSelectedItem());
                pstmt.setString(4, (String)schemaVistaComboBox.getSelectedItem());
                righeInserite = pstmt.executeUpdate();
            
                if(righeInserite != 0){
                    JOptionPane.showMessageDialog(this, "La vista " + nomeVistaTextField.getText() + " è stata inserita correttamente !", "Inserimento Vista effettuato", JOptionPane.INFORMATION_MESSAGE); 
                    pulisciInput();
                } 
                
                if(pstmt != null) pstmt.close();
            }
        }catch(SQLException e) {
            mostraErrore(e);
        }
    }//GEN-LAST:event_insertVistaButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annullaButton;
    private javax.swing.JLabel campoObbLabel;
    private javax.swing.JButton insertVistaButton1;
    private javax.swing.JLabel istruzioni1;
    private javax.swing.JLabel istruzioni2;
    private javax.swing.JLabel istruzioni3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeVistaLabel;
    private javax.swing.JTextField nomeVistaTextField;
    private javax.swing.JComboBox<String> proprVistaComboBox;
    private javax.swing.JLabel proprVistaLabel;
    private javax.swing.JLabel queryVistaLabel;
    private javax.swing.JTextArea queryVistaTextArea;
    private javax.swing.JComboBox<String> schemaVistaComboBox;
    private javax.swing.JLabel schemaVistaLabel;
    // End of variables declaration//GEN-END:variables
}
