/*
 * file: InsertPrivilegio.java
 */
package progettopastoreluca;

/**
 * Pannello che permette l'aggiunta dell'elemento privilegio nel database, richiamando l'apposito oggetto InsertNewPriv;
 * inoltre, questo pannello permette anche l'aggiunta di privilegi (gia esistenti nel database)
 * a ruoli (gia esistenti) richiamando l'apposito oggetto AddPrivToRole. 
 * 
 * @author Luca Pastore
 * @version 2019
 */
public class InsertPrivilegio extends javax.swing.JPanel {
    
    private final InsertNewPriv iNP= new InsertNewPriv();
    private final AddPrivToRole aP = new AddPrivToRole();
    
    /**
     * Creates new form InsertPrivilegio
     */
    public InsertPrivilegio() {
        this.setSize(770,423);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        privButtonGroup = new javax.swing.ButtonGroup();
        istruzioni1 = new javax.swing.JLabel();
        istruzioni2 = new javax.swing.JLabel();
        istruzioni3 = new javax.swing.JLabel();
        insertPrivRadioButton = new javax.swing.JRadioButton();
        addPrivToRoleRadioButton = new javax.swing.JRadioButton();
        insertPrivPanel = new javax.swing.JPanel();

        privButtonGroup.add(insertPrivRadioButton);
        privButtonGroup.add(addPrivToRoleRadioButton);

        istruzioni1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        istruzioni1.setText("In questo pannello è possibile inserire un privilegio, cioè un permesso che può essere assegnato ");

        istruzioni2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        istruzioni2.setText("ad uno o più utenti del database. Inoltre è possibile assegnare un privilegio già presente nel database");

        istruzioni3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        istruzioni3.setText("ad un determinato ruolo esistente.");

        insertPrivRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        insertPrivRadioButton.setText("Inserisci nuovo Privilegio");
        insertPrivRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertPrivRadioButtonActionPerformed(evt);
            }
        });

        addPrivToRoleRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addPrivToRoleRadioButton.setText("Aggiungi Privilegio a Ruolo");
        addPrivToRoleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPrivToRoleRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertPrivPanelLayout = new javax.swing.GroupLayout(insertPrivPanel);
        insertPrivPanel.setLayout(insertPrivPanelLayout);
        insertPrivPanelLayout.setHorizontalGroup(
            insertPrivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        insertPrivPanelLayout.setVerticalGroup(
            insertPrivPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(istruzioni1)
                    .addComponent(istruzioni2)
                    .addComponent(istruzioni3))
                .addContainerGap(36, Short.MAX_VALUE))
            .addComponent(insertPrivPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertPrivRadioButton)
                .addGap(18, 18, 18)
                .addComponent(addPrivToRoleRadioButton)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(istruzioni1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(istruzioni2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(istruzioni3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertPrivRadioButton)
                    .addComponent(addPrivToRoleRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insertPrivPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //metodo che, alla selezione del RadioButton "Inserisci nuovo Privilegio", crea un nuovo pannello InsertNewPriv e lo aggiunge all' insertPrivPanel
    private void insertPrivRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertPrivRadioButtonActionPerformed
        insertPrivPanel.removeAll();
        insertPrivPanel.add(iNP);
        iNP.setVisible(true);
        iNP.creaPrivOggComboBox();
        iNP.creaPrivSisComboBox();
        insertPrivPanel.revalidate();
        insertPrivPanel.repaint();
    }//GEN-LAST:event_insertPrivRadioButtonActionPerformed

    //metodo che, alla selezione del RadioButton "Aggiungi Privilegio a Ruolo", crea un nuovo pannello AddPrivToRole e lo aggiunge all' insertPrivPanel
    private void addPrivToRoleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPrivToRoleRadioButtonActionPerformed
        insertPrivPanel.removeAll();
        insertPrivPanel.add(aP);
        aP.creaSelectRoleComboBox();
        aP.setVisible(true);
        insertPrivPanel.revalidate();
        insertPrivPanel.repaint();
    }//GEN-LAST:event_addPrivToRoleRadioButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addPrivToRoleRadioButton;
    private javax.swing.JPanel insertPrivPanel;
    private javax.swing.JRadioButton insertPrivRadioButton;
    private javax.swing.JLabel istruzioni1;
    private javax.swing.JLabel istruzioni2;
    private javax.swing.JLabel istruzioni3;
    private javax.swing.ButtonGroup privButtonGroup;
    // End of variables declaration//GEN-END:variables
}
