/**
 * file: insertRuolo.java
 */
package progettopastoreluca;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 * Pannello che permette l'aggiunta dell'elemento ruolo nel database;
 * 
 * @author Luca Pastore
 * @version 2019
 */
public class InsertRuolo extends javax.swing.JPanel {

    private PreparedStatement pstmt = null;
    private final String queryIns = "INSERT INTO ruolo(nomeRuolo) VALUES(?)";
    private int righeInserite = 0;
    
    /**
     * Crea nuovo oggetto InsertRuolo
     */
    public InsertRuolo() {
        this.setSize(770, 423);
        initComponents();
    }
    
    //svuota tutti i campi di input del pannello
    public void pulisciInput(){
        nomeRuoloTextField.setText("");
    }
    
    private void mostraErrore(SQLException e) {
        String msg;
        
        msg = "Codice Errore: " + e.getErrorCode() + "\n";
        msg += "Messaggio: " + e.getMessage() + "\n";
        msg += "SQLState: " + e.getSQLState() + "\n";

        JOptionPane.showMessageDialog(this, msg, "Errore", JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        istruzioni1 = new javax.swing.JLabel();
        istruzioni2 = new javax.swing.JLabel();
        istruzioni3 = new javax.swing.JLabel();
        nomeRuoloLabel = new javax.swing.JLabel();
        nomeRuoloTextField = new javax.swing.JTextField();
        insertRuoloButton = new javax.swing.JButton();
        annullaButton = new javax.swing.JButton();
        campoObbLabel = new javax.swing.JLabel();

        istruzioni1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        istruzioni1.setText("Un ruolo è un insieme di privilegi che può essere assegnato ad uno o più utenti del database.");

        istruzioni2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        istruzioni2.setText("In questa sezione è possibile inserire un nuovo ruolo, per l'inserimento di privilegi nel ruolo, ");

        istruzioni3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        istruzioni3.setText("selezionare la sezione \"Privilegio\".");

        nomeRuoloLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomeRuoloLabel.setText("Nome Ruolo  *");

        nomeRuoloTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        insertRuoloButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        insertRuoloButton.setText("Inserisci Ruolo");
        insertRuoloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertRuoloButtonActionPerformed(evt);
            }
        });

        annullaButton.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        annullaButton.setText("Annulla");
        annullaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaButtonActionPerformed(evt);
            }
        });

        campoObbLabel.setText("*  Campo Obbligatorio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(istruzioni1)
                            .addComponent(istruzioni2)
                            .addComponent(istruzioni3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeRuoloLabel)
                                .addGap(118, 118, 118)
                                .addComponent(nomeRuoloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(insertRuoloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(annullaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoObbLabel)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(istruzioni1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(istruzioni2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(istruzioni3)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeRuoloLabel)
                    .addComponent(nomeRuoloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertRuoloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annullaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(campoObbLabel)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //metodo utilizzato per annullare l'inserimento del ruolo
    private void annullaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annullaButtonActionPerformed
        pulisciInput();
    }//GEN-LAST:event_annullaButtonActionPerformed

    private void insertRuoloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertRuoloButtonActionPerformed
        try{ 
            if(nomeRuoloTextField.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Prima di effettuare l'inserimento del ruolo, riempire tutti i campi obbligatori !", "Attenzione", JOptionPane.WARNING_MESSAGE);
            }else{
                pstmt = Database.getDefaultConnection().prepareStatement(queryIns);            
            
                pstmt.setString(1, nomeRuoloTextField.getText());
                righeInserite = pstmt.executeUpdate();
            
                if(righeInserite != 0){
                    JOptionPane.showMessageDialog(this, "Il ruolo " + nomeRuoloTextField.getText() + " è stato inserito correttamente", "Inserimento Schema effettuato", JOptionPane.INFORMATION_MESSAGE); 
                    pulisciInput();
                }
                
                if(pstmt != null) pstmt.close();
            }
            
        }catch(SQLException e) {
            mostraErrore(e);
        }
    }//GEN-LAST:event_insertRuoloButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annullaButton;
    private javax.swing.JLabel campoObbLabel;
    private javax.swing.JButton insertRuoloButton;
    private javax.swing.JLabel istruzioni1;
    private javax.swing.JLabel istruzioni2;
    private javax.swing.JLabel istruzioni3;
    private javax.swing.JLabel nomeRuoloLabel;
    private javax.swing.JTextField nomeRuoloTextField;
    // End of variables declaration//GEN-END:variables
}
